// DHT sensor library - Version: 1.4.2
#include <DHT.h>
#include <DHT_U.h>

#define dhtpin 2
#define dhttype DHT22

DHT dht(dhtpin, dhttype);

unsigned long myTime;
unsigned int Time;


/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/230c0d34-12ea-4e55-9bc4-8e1fafe9b723

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor temperature;
  CloudLight led_state;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1000);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  pinMode(LED_BUILTIN, OUTPUT);
  dht.begin();

  Serial.println("start");
  delay(1000);

}

void loop() {
  ArduinoCloud.update();
  
  myTime = millis();

  Time = myTime / 1000;
  if (Time % 30 == 0)
  {
    temperature = dht.readTemperature();
  }
  delay(1000);

}

void onLedStateChange() {
  if (led_state)
    digitalWrite(LED_BUILTIN, HIGH);
  else
    digitalWrite(LED_BUILTIN, LOW);
}
